# Generated by Django 4.1 on 2022-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Введите имя автора', max_length=100, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Введите краткое описание книги', max_length=1000, verbose_name='Аннотация книги'),
        ),
    ]
